name: Build example.typ
on: push

jobs:
  build-example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: typst-community/setup-typst@v3
        name: Install Typst

      - run: "typst compile examples/example.typ --root ."
        name: Compile the examples
